# -*- coding: utf-8 -*-
"""adultDeploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fA4q9f1iyrL8HFZQIdgBO0BPttjefplI
"""

# Define the variable
folder_name = "/content/drive/My Drive/Colab Notebooks/Machine_learning IF6/01_adult_klasifikasi"

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import sys
sys.path.append(f'{folder_name}')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
import joblib

classifier_dt = joblib.load(f'{folder_name}/best_income_predictor_model.joblib')

classifier_dt

age = float(input("masukan age : "))

workclass = {'Never-worker':0, 'Without-pay':1, 'Private':7, 'Self-emp-inc':2, 'Self-emp-not-inc':6, 'Local-gov':3, 'State-gov':5, 'Federal-gov':4}
print(workclass)

workclass = int(input('Masukan workclass : '))

fnlwgt = float(input('Masukan fnlwgt : '))

education = {'Preschool':1.0, '1st-4th':2.0, '5th-6th':13.8, '7th-8th':4.0, '9th':5.0, '10th':6.8, '11th':7.0, '12th':8.0, 'HS-grad':9.0, 'Some-college':10.0, 'Assoc-voc':11.0, 'Assoc-acdm':12.0, 'Bachelors':13.0, 'Masters':14.0, 'Prof-school':15.0, 'Doctorate':16.0}
print(education)

education_num = float(input('Masukan education_num : '))

marital_status = {'Never-married':0, 'Married-civ-spouse':1, 'Divorced':2, 'Married-spouse-absent':3, 'Separated':6, 'Married-AF-spouse':5, 'Widowed':4}
print(marital_status)

marital_status = int(input('Masukan marital_status : '))

occupation = {'Adm-clerical': 1, 'Exec-managerial': 2, 'Handlers-cleaners':3,'Prof-specialty': 4, 'Other-service': 5, 'Sales':6, 'Craft-repair':7,'Transport-moving': 8, 'Farming-fishing': 9,'Machine-op-inspct':10,'Tech-support': 11, 'Protective-serv': 12, 'Armed-Forces':13, 'Priv-house-serv':14}
print(occupation)

occupation = int(input('Masukan occupation : '))

relationship = {'Not-in-family':1, 'Husband':2, 'Wife':3, 'Own-child':4, 'Unmarried':0, 'Other-relative':5}
print(relationship)

relationship = int(input('Masukan relationship : '))

race = {'White':1, 'Black':2, 'Asian-Pac-Islander':3, 'Amer-Indian-Eskimo':4, 'Other':5}
print(race)

race = int(input('Masukan race : '))

sex = {'Female':0, 'Male':1}
print(sex)

sex = int(input('Masukan sex : '))

hours_per_week = float(input('Masukan hours_per_week : '))

nativecountry = {'United-States': 1, 'Cuba': 2, 'Jamaica': 3, 'India': 4,'Mexico':5, 'South': 6, 'Puerto-Rico': 7, 'Honduras': 8, 'England': 9, 'Canada': 10,'Germany':11, 'Iran':12, 'Philippines': 13, 'Italy': 14, 'Poland': 15,'Columbia': 16, 'Cambodia': 17, 'Thailand': 18, 'Ecuador':19, 'Laos':20,'Taiwan': 21, 'Haiti':22, 'Portugal':23, 'Dominican-Republic': 24,'El-Salvador': 25, 'France': 26, 'Guatemala': 27, 'China': 28, 'Japan': 29,'Yugoslavia':30, 'Peru':31, 'Outlying-US(Guam-USVI-etc)':32, 'Scotland': 33,'Trinadad&Tobago': 34, 'Greece': 35, 'Nicaragua': 36, 'Vietnam': 37, 'Hong': 38,'Ireland': 39, 'Hungary': 40, 'Holand-Netherlands':41}
print(nativecountry)

nativecountry = int(input('Masukan nativecountry : '))

pred_args = np.array([age,workclass,fnlwgt,education_num,marital_status,occupation,relationship,race,sex,hours_per_week,nativecountry])
pred_args = pred_args.reshape(1,-1)

pred_args

model_prediction = classifier_dt.predict(pred_args)[0]

model_prediction

labels = {0:'<=50K', 1:'>50K'}

prediction = labels[model_prediction]
print('hasil prediksi adalah : ', model_prediction)